// commonjs, every files is module (by default)
//  modules - Encapsulate code (only share minimum)
const names = require('./3-name')
const sayHi = require('./4-utils')
const jilabaj =require('./5-alternative-favor')
require('./6-mind-saver')
//sayHi('mani')
//sayHi(names.hari)
//sayHi(names.pater)
console.log(jilabaj)